# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CameraView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class CameraWidget(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        Form = self
        Form.setObjectName("CameraWidget")
        Form.setAccessibleName("CameraWidget")
        # Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_startCamera = QtWidgets.QPushButton(Form)
        self.pushButton_startCamera.setObjectName("pushButton_startCamera")
        self.verticalLayout.addWidget(self.pushButton_startCamera)
        self.pushButton_stopCamera = QtWidgets.QPushButton(Form)
        self.pushButton_stopCamera.setObjectName("pushButton_stopCamera")
        self.verticalLayout.addWidget(self.pushButton_stopCamera)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_startCamera.setText(_translate("Form", "Start Camera"))
        self.pushButton_stopCamera.setText(_translate("Form", "Stop Camera"))
